site_name: unleash-client-python

nav:
  - Home: index.md
  - UnleashClient: unleashclient.md
  - Strategy: strategy.md
  - Custom Strategies: customstrategies.md
  - Changelog: changelog.md
  - Development: development.md
  - Resources: resources.md

theme: readthedocs
